---
- name: Verify apache2 is present
  apt:
    name: apache2
    state: present
- name: Verify apache2-doc is present
  apt:
    name: apache2-doc
    state: present
- name: Verify apache2-utils is present
  apt:
    name: apache2-utils
    state: present
- name: Update modified webfiles
  copy:
    src: "{{playbook_dir}}/src/html"
    dest: "{{apache2_www_dir}}/"
    owner: root
    group: root
    mode: 0644
- name: Update modified config
  template:
    src: apache2.conf.j2
    dest: "{{apache2_conf_dir}}/apache2.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache
- name: Ensure apache is running
  action: service name=apache2 state=started
